<a href="https://colab.research.google.com/github/salfetka03/salfetniza/blob/main/Numpy_solutions2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Импортируйте библиотеку NumPy

In [ ]:
import numpy

Создайте массив из 10 нулей

In [ ]:
import numpy as NP
a=NP.ones(10)
print(a)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать массив из 10 единиц

In [ ]:
b=NP.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать массив из 10 пятерок


In [ ]:
c=NP.zeros(10)+5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


 Создать массив из целых чисел от 10 до 50


In [ ]:
d=NP.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Создать массив из четных чисел от 10 до 50

In [ ]:
a1 = [i for i in range(0,51,2)]
print(a1)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
matrix1 = NP.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("Матрица:\n", matrix1)

Матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Создать единичную матрицу 3x3

In [ ]:
print(NP.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
print(NP.random.rand())

0.13485122352484757


Используйте NumPy для генерации массива из 25 случайных чисел,
взятых из стандартного нормального распределения

In [ ]:
print(NP.random.normal(size=25))

[ 0.02639252  1.91800907  0.20341408 -0.32697193  2.18416881 -0.95404273
  0.21040373 -1.7723107  -0.50429406  2.74601313  0.10392141  1.42814973
 -0.8769968  -0.7682804   0.1112273  -1.14806912  0.96479408 -0.53854764
  0.47766241  0.17315783 -0.19355734  0.49279084  0.24632605  0.18365242
  0.25665565]


Создайте следующую матрицу используя функции библиотеки NumPy

In [ ]:
d = NP.arange(0.01,1.01,0.01).reshape(10,10)
print(d)             

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Дана стартовая матрица (обязательно запустите код ниже в вашем
решении!). Эта матрица будет использоваться в последующих задачах

In [ ]:
mat = NP.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу
из стартовой:

In [ ]:
print('1=',mat[2:,:1])

1= [[11]
 [16]
 [21]]


Написать код обращения к элементу который вернет значение 20 из
стартовой матрицы задачи l.

In [ ]:
print(mat[3,3])

19


Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
array ([2]),
        [7],
        [12]])
            

In [ ]:
print(mat[:3, 1 :2])

[[ 2]
 [ 7]
 [12]]


задание "о"

In [ ]:
print(mat[4, :])

[21 22 23 24 25]


задание "р"

In [ ]:
print(mat[3:, 0:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


задание "q"

In [ ]:
print(mat.sum())

325


задание "r"

In [ ]:
print(mat.std())

7.211102550927978


задание "s"

In [ ]:
print(mat.sum(axis=0))

[55 60 65 70 75]
